### ISSUE TITLE
Whitelist based on dynamic dns entry

### ISSUE THREAD

**Issue by ckarnik** [jjxtra/Windows-IP-Ban-Service#10]
Will it be possible to add a whitelist host name in the config file in the future?   Entering a fixed IP in the white-list does not work well in the scenario where ISP frequently changes IP for customers.

These days, there are many free and paid dynamic dns host providers (no-ip.com, dyndns, etc).  Even router firmware like DD-WRT supports updating dynamic host entries.

This does have a man in the middle attack possibility, however, that can be mitigated by the use of opendns servers.

**Comment by akeilox** [comment]
This is a very old thread, stumpled upon googling. Can I check if this DynamicDomainWhiteList is inside ipban.config ?

**Comment by jjxtra** [comment]
You can put url's or host names in the whitelist, yes. If you have lots of ips, the FirewallUriRules property is better.

**Comment by jjxtra** [comment]
Also, the Whitelist property mentions urls and host names:

```
`Whitelist` - comma separated list of ip addresses, cidr masks, urls or DNS names that are never banned. These will be added to a whitelist rule in the firewall. Put your static ip address in here if you have one, that way you don't accidentally lock yourself out. Whitelist takes precedence over blacklist. If you use a url, each ip entry in the response should be newline delimited, example: https://uptimerobot.com/inc/files/ips/IPv4andIPv6.txt. Urls in this config entry should have a small number of ip addresses.
```

**Comment by akeilox** [comment]
Got it. It was not immediately clear with mention of " If you use a url, the response should be text and newline delimited", thought url reference was for list of ips.
Thanks for clarification @jjxtra
