### ISSUE TITLE
Rule firewall fail when there is many stored IPs

### ISSUE THREAD

**Issue by A13xs** [jjxtra/Windows-IP-Ban-Service#15]
I established the rule ExpireTime to 00: 00: 00: 00 to never forget an IP

Banscript is very long. Exceeds the maximum length of command line string (8191 characters)  and fails.

Any solution?

**Comment by jjxtra** [comment]
Hi there. I'll see if there's a way to run the script from a file rather than command line.

**Comment by eossipov** [comment]
What about merging some of the IP's, into blocks also? stands to reason, if there are many infractions within specific blocks, then those could be merged into the larger block and the ip's archived? 
just a thought.

**Comment by jjxtra** [comment]
Great ideas, unfortunately my bandwidth is severely limited at the moment. If I get a free day sometime I may take a stab at this.

**Comment by jjxtra** [comment]
This should be resolved. Multiple rules are now supported.
