### ISSUE TITLE
[New Feature] PPTP

### ISSUE THREAD

**Issue by thiagocpv** [jjxtra/Windows-IP-Ban-Service#17]
Hi there!

This is awesome tool to protect the servers with RDP opened. Congrats!

May be a new feature is to protect the PPTP 1723 like 3389.

Cheers!

**Comment by jjxtra** [comment]
If the failed login attempt gets stored in the event viewer and contains an ip address and port, it can be blocked without code changes.

**Comment by jjxtra** [comment]
If you can open a new issue with the appropriate event viewer xml, I will add it to the list of default filters

**Comment by thiagocpv** [comment]
Hi @jjxtra 

How can update my existing version ? I don't have Visual Studio to compile the source......

Thanks.

**Comment by jjxtra** [comment]
http://www.digitalruby.com/securing-your-windows-dedicated-server/

-- Jeff

**Comment by thiagocpv** [comment]
@jjxtra Thank you very much!
Great Job!
