### ISSUE TITLE
[New Feature] e-mail alert

### ISSUE THREAD

**Issue by thiagocpv** [jjxtra/Windows-IP-Ban-Service#18]
Hi there!

New feature: email alert sent when the IP was blocked or summary at the end of day to the attempts and IP's blockeds.

**Comment by Rambaldi2003** [comment]
hello, I have implemented some time this function

**Comment by thiagocpv** [comment]
Hello @Rambaldi2003 

Yes, I am interested. Can you share please?

Thanks buddy.

**Comment by thiagocpv** [comment]
Hello @Rambaldi2003

Yes, I am interested. Can you share please?

Thanks buddy.

**Comment by Rambaldi2003** [comment]
Hi I have already posted the code

**Comment by Rambaldi2003** [comment]
look this https://github.com/jjxtra/Windows-IP-Ban-Service/issues/19

**Comment by thiagocpv** [comment]
Hi !How can I set up this code there?‎ I dont have visual studio.....                                                                                                                                                                                                                                                                          Enviado do meu smartphone BlackBerry 10.                                                                                                                                                                                                                                         De: Rambaldi2003Enviada: sexta-feira, 17 de julho de 2015 09:29Para: jjxtra/Windows-IP-Ban-ServiceResponder a: jjxtra/Windows-IP-Ban-ServiceCc: thiagocpvAssunto: Re: [Windows-IP-Ban-Service] [New Feature] e-mail alert (#18)look this #19

—Reply to this email directly or view it on GitHub.

**Comment by Rambaldi2003** [comment]
Then you have the owner of the software integrate my code and publish it.
I can give you my executable but then if the owner makes changes that I do ....
However, if you want I can give my executable. hello

**Comment by thiagocpv** [comment]
And how can I change de variables like smtp, port, email, etc? If you give
me the executable, I can't change the variables, right?

**Comment by Rambaldi2003** [comment]
you can change variables in config file

**Comment by thiagocpv** [comment]
Ah ok, so can you send me the executable please?                                                                                                                                                                                                                                                                          Enviado do meu smartphone BlackBerry 10.                                                                                                                                                                                                                                         De: Rambaldi2003Enviada: sexta-feira, 17 de julho de 2015 13:06Para: jjxtra/Windows-IP-Ban-ServiceResponder a: jjxtra/Windows-IP-Ban-ServiceCc: thiagocpvAssunto: Re: [Windows-IP-Ban-Service] [New Feature] e-mail alert (#18)you can change variables in config file

—Reply to this email directly or view it on GitHub.

**Comment by thytetgc** [comment]
re-downloas, please...
