### ISSUE TITLE
Email Notify

### ISSUE THREAD

**Issue by Rambaldi2003** [jjxtra/Windows-IP-Ban-Service#19]
IPBanService.cs
Add this function
        private void SendMail(string ipAddress, string userName)
        {
            //config.SendMail
            string messaggio = "";
            messaggio = "Ban IP: " +  ipAddress + " User Name: " + userName;
            try
            {
                MailMessage message = new MailMessage(config.MailFrom, config.MailTo, "IP Banned SERVER: " + config.ServerNameIP , messaggio);
                SmtpClient emailClient = new SmtpClient(config.MailSmtp);
                System.Net.NetworkCredential smtpUserInfo = new System.Net.NetworkCredential(config.MailFrom, config.MailPW);
                emailClient.UseDefaultCredentials = false;
                emailClient.EnableSsl = config.MailSSL;
                emailClient.Credentials = smtpUserInfo;
                emailClient.Send(message);
                Log.Write(LogLevel.Info, "Message Sent");
            }
            catch (Exception ex)
            {
                Log.Write(LogLevel.Warning, "Send Mail Error {0}", ex.ToString());
            }
        }

Modify this function
        private void ProcessIPAddress(string ipAddress, XmlDocument doc)
        {
            if (string.IsNullOrWhiteSpace(ipAddress))
            {
                return;
            }

            string userName = null;
            XmlNode userNameNode = doc.SelectSingleNode("//Data[@Name='TargetUserName']");
            if (userNameNode != null)
            {
                userName = userNameNode.InnerText.Trim();
            }

            if (config.IsWhiteListed(ipAddress))
            {
                Log.Write(LogLevel.Info, "Ignoring whitelisted ip address {0}, user name: {1}", ipAddress, userName);
            }
            else
            {
                lock (ipBlocker)
                {
                    // Get the IPBlockCount, if one exists.
                    IPBlockCount ipBlockCount;
                    ipBlocker.TryGetValue(ipAddress, out ipBlockCount);
                    if (ipBlockCount == null)
                    {
                        // This is the first failed login attempt, so record a new IPBlockCount.
                        ipBlockCount = new IPBlockCount();
                        ipBlocker[ipAddress] = ipBlockCount;
                    }

                    // Increment the count.
                    ipBlockCount.IncrementCount();

                    Log.Write(LogLevel.Info, "Incrementing count for ip {0} to {1}, user name: {2}", ipAddress, ipBlockCount.Count, userName);

                    // check for the target user name for additional blacklisting checks                    
                    bool blackListed = config.IsBlackListed(ipAddress) || (userName != null && config.IsBlackListed(userName));

                    // if the ip is black listed or they have reached the maximum failed login attempts before ban, ban them
                    if (blackListed || ipBlockCount.Count >= config.FailedLoginAttemptsBeforeBan)
                    {
                        // if they are not black listed OR this is the first increment of a black listed ip address, perform the ban
                        if (!blackListed || ipBlockCount.Count >= 1)
                        {
                            if (!ipBlockerDate.ContainsKey(ipAddress))
                            {
                                Log.Write(LogLevel.Error, "Banning ip address: {0}, user name: {1}, black listed: {2}, count: {3}", ipAddress, userName, blackListed, ipBlockCount.Count);
                                ipBlockerDate[ipAddress] = DateTime.UtcNow;
                                ExecuteBanScript();
                               // Add This **********************************
                                if (config.SendMail){
                                    SendMail(ipAddress, userName);
                                }
                               //************************************************  
                            }
                        }
                        else
                        {
                            Log.Write(LogLevel.Info, "Ignoring previously banned black listed ip {0}, user name: {1}, ip should already be banned", ipAddress, userName);
                        }
                    }
                    else if (ipBlockCount.Count > config.FailedLoginAttemptsBeforeBan)
                    {
                        Log.Write(LogLevel.Warning, "Got event with ip address {0}, count {1}, ip should already be banned", ipAddress, ipBlockCount.Count);
                    }
                }
            }
        }

Modify IPBanConfig.cs 
    public class IPBanConfig
    {
        private ExpressionsToBlock expressions;
        private int failedLoginAttemptsBeforeBan = 5;
        private TimeSpan banTime = TimeSpan.FromDays(1.0d);
        private string banFile = "banlog.txt";
        private TimeSpan expireTime = TimeSpan.FromDays(1.0d);
        private TimeSpan cycleTime = TimeSpan.FromMinutes(1.0d);
        private string ruleName = "BlockIPAddresses";
        private readonly HashSet<string> whiteList = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private Regex whiteListRegex;
        private readonly HashSet<string> blackList = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private Regex blackListRegex;
        private readonly HashSet<string> allowedUserNames = new HashSet<string>();
        private bool banFileClearOnRestart;

       // Add This ********************************************************
        private bool sendMail;
        private bool mailSSL;
        private string mailFrom = "" ;
        private string mailTo = "";
        private string mailSmtp = "";
        private string mailPW = "";
        private string serverNameIP = "";
       // *******************************************************************************

        public IPBanConfig()
        {
            ConfigurationManager.RefreshSection("appSettings");
            ConfigurationManager.RefreshSection("configSections");
            ConfigurationManager.RefreshSection("nlog");
            ConfigurationManager.RefreshSection("ExpressionsToBlock");

            string value = ConfigurationManager.AppSettings["FailedLoginAttemptsBeforeBan"];
            failedLoginAttemptsBeforeBan = int.Parse(value, CultureInfo.InvariantCulture);

            value = ConfigurationManager.AppSettings["BanTime"];
            banTime = TimeSpan.Parse(value, CultureInfo.InvariantCulture);

            value = ConfigurationManager.AppSettings["BanFile"];
            banFile = value;
            if (!Path.IsPathRooted(banFile))
            {
                banFile = Path.GetFullPath(banFile);
            }
            value = ConfigurationManager.AppSettings["BanFileClearOnRestart"];
            if (!bool.TryParse(value, out banFileClearOnRestart))
            {
                banFileClearOnRestart = true;
            }

          // Add this **************************************************************************

            value = ConfigurationManager.AppSettings["SendMail"];
            if (!bool.TryParse(value, out sendMail))
            {
                sendMail = true;
            }

            value = ConfigurationManager.AppSettings["MailSSL"];
            if (!bool.TryParse(value, out mailSSL))
            {
                mailSSL = true;
            }
           // *********************************************************************************************

            value = ConfigurationManager.AppSettings["ExpireTime"];
            expireTime = TimeSpan.Parse(value, CultureInfo.InvariantCulture);
            
            value = ConfigurationManager.AppSettings["CycleTime"];
            cycleTime = TimeSpan.Parse(value, CultureInfo.InvariantCulture);

            value = ConfigurationManager.AppSettings["RuleName"];
            ruleName = value;

           // Add this ********************************************************************************
            value = ConfigurationManager.AppSettings["MailFrom"];
            mailFrom = value;

            value = ConfigurationManager.AppSettings["MailTo"];
            mailTo = value;

            value = ConfigurationManager.AppSettings["MailPW"];
            mailPW = value;

            value = ConfigurationManager.AppSettings["MailSmtp"];
            mailSmtp = value;

            value = ConfigurationManager.AppSettings["ServerNameIP"];
            serverNameIP = value;            
            //************************************************************************************************
            
            
            PopulateList(whiteList, ref whiteListRegex, ConfigurationManager.AppSettings["Whitelist"], ConfigurationManager.AppSettings["WhitelistRegex"]);
            PopulateList(blackList, ref blackListRegex, ConfigurationManager.AppSettings["Blacklist"], ConfigurationManager.AppSettings["BlacklistRegex"]);
            Regex ignored = null;
            PopulateList(allowedUserNames, ref ignored, ConfigurationManager.AppSettings["AllowedUserNames"], null);
            expressions = (ExpressionsToBlock)System.Configuration.ConfigurationManager.GetSection("ExpressionsToBlock");

            foreach (ExpressionsToBlockGroup group in expressions.Groups)
            {
                foreach (ExpressionToBlock expression in group.Expressions)
                {
                    expression.Regex = (expression.Regex ?? string.Empty).Trim();
                    expression.RegexObject = new Regex(expression.Regex, RegexOptions.IgnoreCase | RegexOptions.Singleline);
                }
            }
        }
// Add this declaratrion
        public string MailFrom { get { return mailFrom; } }

        /// <summary>
        /// Mail TO
        /// </summary>
        public string MailTo { get { return mailTo; } }

        /// <summary>
        /// Password Mail
        /// </summary>
        public string MailPW { get { return mailPW; } }

        /// <summary>
        /// SMTP Server
        /// </summary>
        public string MailSmtp { get { return mailSmtp; } }

        /// <summary>
        /// Server Name or IP
        /// </summary>
        public string ServerNameIP { get { return serverNam

       /// <summary>
        /// Send Mail true false
        /// </summary>
        public bool SendMail { get { return sendMail; } }

        /// <summary>
        /// Mail SSL
        /// </summary>
        public bool MailSSL { get { return mailSSL; } }

      //***********************************************************************************

In App.Config Add this
    
    <add key="SendMail" value="true" />

    <add key="MailFrom" value="Mail from" />

    <add key="MailTo" value="mail to" />

    <add key="MailPW" value="Mail Password" />

    <add key="MailSSL" value="true" />

    <add key="MailSMTP" value="mail server" />
    
    <add key="ServerNameIP" value="server IP or name server" />    
// **********************************************************************************************************

ok I hope you did not forget anything, if there is no write me as well.
I also wrote a small software that crypt password mail so as not to put the password in clear text in the config. I added a class to decrypt the password when the software needs to send the notification email. If you are interested please add them too.
Hello
Michele Sinesi

p-s. sorry for my english

**Comment by jjxtra** [comment]
If you do a pull request it will be a lot easier to get this in.

**Comment by jjxtra** [comment]
Closing this issue. If you want this to make it into the main branch, please submit a pull request.
