### ISSUE TITLE
RDP Gateway protection

### ISSUE THREAD

**Issue by jtrott** [jjxtra/Windows-IP-Ban-Service#23]
I found the following section in the cfg file will block brute force attempts on a RDP Gateway server.

       
      <Group>
        <Keywords>0x4000000000000000</Keywords>
        <Path>Microsoft-Windows-TerminalServices-Gateway/Operational</Path>
        <Expressions>
          <Expression>
            <XPath>//EventID</XPath>
            <Regex>312</Regex>
          </Expression>
          <Expression>
            <XPath>//IpAddress</XPath>
            <Regex>
              <![CDATA[
                (?<ipaddress>.+):.*
              ]]>
            </Regex>
          </Expression>
        </Expressions>
      </Group>

**Comment by Rambaldi** [comment]
not work, crash service.

**Comment by jtrott** [comment]
Hi.

I have this working on 2 different servers, have you double checked your XML syntax after you pasted in the addition to the groups section?

**Comment by jtrott** [comment]
Bugger.

Looks like that eventid doesn't indicate a failed login, just a login request. Back to the drawing board, unless anyone knows where to find an event that indicates a failed login that includes the client IP address?

**Comment by Rambaldi** [comment]
the error is in <Path>Microsoft-Windows-TerminalServices-Gateway/Operational</Path>
if remove "Microsoft-Windows-TerminalServices-Gateway/"  the group not crash the  service.

Leaving only  "Operational"  the group working the same?


  <Group>
    <Keywords>0x4000000000000000</Keywords>
    <Path>Operational</Path>
    <Expressions>
      <Expression>
        <XPath>//EventID</XPath>
        <Regex>312</Regex>
      </Expression>
      <Expression>
        <XPath>//IpAddress</XPath>
        <Regex>
          <![CDATA[
            (?<ipaddress>.+):.*
          ]]>
        </Regex>
      </Expression>
    </Expressions>
  </Group>

**Comment by jjxtra** [comment]
Crashes on Windows 10 for me, not willing to add this until it is tested further

**Comment by jtrott** [comment]
Yep, it doesn't do what I was hoping in any case, so no point in adding it. We have to wait until Microsoft does proper logging for failed login attempts.
