### ISSUE TITLE
Add support for whitelisting of IP ranges and CIDR notation

### ISSUE THREAD

**Issue by thnilsen** [jjxtra/Windows-IP-Ban-Service#24]
It would be good to see support for whitelisting of ip ranges and CIDR notations, something along the lines of:

<add key="Whitelist" value="192.168.10.0/16, 8.8.8.8-8.8.8.10, 192.168.1.4" />

**Comment by jjxtra** [comment]
Regex whitelisting is supported via WhitelistRegex in the config.
http://www.regular-expressions.info/numericranges.html
