### ISSUE TITLE
windows 2012 error

### ISSUE THREAD

**Issue by Rambaldi** [jjxtra/Windows-IP-Ban-Service#25]
hi in windows 2012 have this error:

`2017-06-27 08:19:45.8561|INFO|FileLogger|Parsing as dns failed '-'`
`2017-06-27 08:19:45.8561|WARN|FileLogger|Regex (?<ipaddress>.+) did not match any nodes with xpath //Data[@Name='IpAddress']`
`2017-06-27 08:19:45.8561|WARN|FileLogger|No nodes found for xpath //Data[@Name='Workstation']`
`2017-06-27 08:19:45.8561|INFO|FileLogger|Processing xml: <Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-A5BA-3E3B0328C30D}'/><EventID>4625</EventID><Version>0</Version><Level>0</Level><Task>12544</Task><Opcode>0</Opcode><Keywords>0x8010000000000000</Keywords><TimeCreated SystemTime='2017-06-27T06:19:23.687982300Z'/><EventRecordID>12950596</EventRecordID><Correlation/><Execution ProcessID='568' ThreadID='6796'/><Channel>Security</Channel><Computer>mypcname</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>S-1-0-0</Data><Data Name='SubjectUserName'>-</Data><Data Name='SubjectDomainName'>-</Data><Data Name='SubjectLogonId'>0x0</Data><Data Name='TargetUserSid'>S-1-0-0</Data><Data Name='TargetUserName'>MADRID</Data><Data Name='TargetDomainName'></Data><Data Name='Status'>0xc000006d</Data><Data Name='FailureReason'>%%2313</Data><Data Name='SubStatus'>0xc0000064</Data><Data Name='LogonType'>3</Data><Data Name='LogonProcessName'>NtLmSsp </Data><Data Name='AuthenticationPackageName'>NTLM</Data><Data Name='WorkstationName'></Data><Data Name='TransmittedServices'>-</Data><Data Name='LmPackageName'>-</Data><Data Name='KeyLength'>0</Data><Data Name='ProcessId'>0x0</Data><Data Name='ProcessName'>-</Data><Data Name='IpAddress'>-</Data><Data Name='IpPort'>-</Data></EventData></Event>`
`2017-06-27 08:19:45.8561|INFO|FileLogger|Parsing as IP failed, checking dns '-'`

in windows 2016 work correctly
You can help me Thank you

Miky

**Comment by Rambaldi** [comment]
This silence worries me :(

**Comment by RoboMWM** [comment]
> This silence worries me :(

It's been 3 days.

**Comment by jjxtra** [comment]
Have you setup the local security policy properly as instructed in readme file?

**Comment by jjxtra** [comment]
The latest version of the code shouldn't have this problem as it reads another separate area of the event viewer which does have the ip address.

**Comment by Rambaldi** [comment]
ok thank you
