### ISSUE TITLE
IPBan.exe.config

### ISSUE THREAD

**Issue by frapie** [jjxtra/Windows-IP-Ban-Service#28]
[IPBan.exe.config.txt](https://github.com/jjxtra/Windows-IP-Ban-Service/files/1140796/IPBan.exe.config.txt)

hi

I setup the whitelist but it still seems to block the address's I put in it which are 10.0.0.0/16

tried whitelist and regex still not working

anything I need to do?

I am using on windows 2016 server
Exchange 2016

it works great at adding them to the firewall but just want to be able to exclude the internal subnet

any help would be appreciated, also thank you for this great application

**Comment by jjxtra** [comment]
Thanks I'll take a look

**Comment by frapie** [comment]
appreciate it

**Comment by jjxtra** [comment]
You need to use the WhitelistRegex. The whitelist is simply a hard-coded list, no wildcard or regex in that one.
