### ISSUE TITLE
not error just question

### ISSUE THREAD

**Issue by rabi29** [jjxtra/Windows-IP-Ban-Service#29]
i try with server 2016eand it work fine.
but i have rdpweb and ipban don t work .
May be have you a solution fot rdweb.

great job

**Comment by jjxtra** [comment]
Check your event viewer for the failed login attempt from rdpweb. Post your XML here and I will add it to the default config.

**Comment by rabi29** [comment]
hi,
i think is not possible with event log ,because event log dont give ip adress with rdweb.
i see another soft like rdguard (not free) for testing and i see rdguard use iis log for rdweb.
i don t know if you can do same.

rdpguard count in iss log how many ip try to connect and after 3 rdpguard drop ip in firewall.

i hope  you understannd ,my English is not good.

best regards

**Comment by jjxtra** [comment]
Please post an example XML from the event viewer and I will add it.

**Comment by rabi29** [comment]
hi

> - <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" /> 
  <EventID>4625</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>12544</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8010000000000000</Keywords> 
  <TimeCreated SystemTime="2017-08-23T09:55:45.054985800Z" /> 
  <EventRecordID>268279</EventRecordID> 
  <Correlation ActivityID="{AFF447A8-1949-0000-BC47-F4AF4919D301}" /> 
  <Execution ProcessID="672" ThreadID="4344" /> 
  <Channel>Security</Channel> 
  <Computer>eao-cal.eao.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="SubjectUserSid">S-1-5-82-604604840-3341247844-1790606609-4006251754-2470522317</Data> 
  <Data Name="SubjectUserName">RDWebAccess</Data> 
  <Data Name="SubjectDomainName">IIS APPPOOL</Data> 
  <Data Name="SubjectLogonId">0x234ed94</Data> 
  <Data Name="TargetUserSid">S-1-0-0</Data> 
  <Data Name="TargetUserName">olivierbn, b</Data> 
  <Data Name="TargetDomainName">eao</Data> 
  <Data Name="Status">0xc000006d</Data> 
  <Data Name="FailureReason">%%2313</Data> 
  <Data Name="SubStatus">0xc0000064</Data> 
  <Data Name="LogonType">3</Data> 
  <Data Name="LogonProcessName">Advapi</Data> 
  <Data Name="AuthenticationPackageName">Negotiate</Data> 
  <Data Name="WorkstationName">EAO-CAL</Data> 
  <Data Name="TransmittedServices">-</Data> 
  <Data Name="LmPackageName">-</Data> 
  <Data Name="KeyLength">0</Data> 
  <Data Name="ProcessId">0x1688</Data> 
  <Data Name="ProcessName">C:\Windows\System32\inetsrv\w3wp.exe</Data> 
  <Data Name="IpAddress">-</Data> 
  <Data Name="IpPort">-</Data> 
  </EventData>
  </Event>

> 
you can see no ip adress for rdweb
IIS log

> 2017-08-22 19:11:50 192.168.50.111 POST /RDWeb/Pages/fr-FR/login.aspx ReturnUrl=%2FRDWeb%2FPages%2Ffr-FR%2FDefault.aspx 443 - 90.150.85.125 Mozilla/5.0+(Windows+NT+10.0;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko https://test2.liberasys.com/RDWeb/Pages/fr-FR/login.aspx?ReturnUrl=%2FRDWeb%2FPages%2Ffr-FR%2FDefault.aspx 200 0 0 

> 
may be i can have ip in event viewer but actually i don t find how

best regerd

**Comment by jjxtra** [comment]
I need the XML, in the event viewer there should be a details or XML tab / button you can select.

**Comment by rabi29** [comment]
Sorry :)

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" /> 
  <EventID>4625</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>12544</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8010000000000000</Keywords> 
  <TimeCreated SystemTime="2017-08-23T09:55:45.054985800Z" /> 
  <EventRecordID>268279</EventRecordID> 
  <Correlation ActivityID="{AFF447A8-1949-0000-BC47-F4AF4919D301}" /> 
  <Execution ProcessID="672" ThreadID="4344" /> 
  <Channel>Security</Channel> 
  <Computer>eao-cal.eao.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="SubjectUserSid">S-1-5-82-604604840-3341247844-1790606609-4006251754-2470522317</Data> 
  <Data Name="SubjectUserName">RDWebAccess</Data> 
  <Data Name="SubjectDomainName">IIS APPPOOL</Data> 
  <Data Name="SubjectLogonId">0x234ed94</Data> 
  <Data Name="TargetUserSid">S-1-0-0</Data> 
  <Data Name="TargetUserName">olivierbn, b</Data> 
  <Data Name="TargetDomainName">eao</Data> 
  <Data Name="Status">0xc000006d</Data> 
  <Data Name="FailureReason">%%2313</Data> 
  <Data Name="SubStatus">0xc0000064</Data> 
  <Data Name="LogonType">3</Data> 
  <Data Name="LogonProcessName">Advapi</Data> 
  <Data Name="AuthenticationPackageName">Negotiate</Data> 
  <Data Name="WorkstationName">EAO-CAL</Data> 
  <Data Name="TransmittedServices">-</Data> 
  <Data Name="LmPackageName">-</Data> 
  <Data Name="KeyLength">0</Data> 
  <Data Name="ProcessId">0x1688</Data> 
  <Data Name="ProcessName">C:\Windows\System32\inetsrv\w3wp.exe</Data> 
  <Data Name="IpAddress">-</Data> 
  <Data Name="IpPort">-</Data> 
  </EventData>
  </Event>

**Comment by rabi29** [comment]
` <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" /> 
  <EventID>4625</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>12544</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8010000000000000</Keywords> 
  <TimeCreated SystemTime="2017-08-23T09:55:45.054985800Z" /> 
  <EventRecordID>268279</EventRecordID> 
  <Correlation ActivityID="{AFF447A8-1949-0000-BC47-F4AF4919D301}" /> 
  <Execution ProcessID="672" ThreadID="4344" /> 
  <Channel>Security</Channel> 
  <Computer>eao-cal.eao.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="SubjectUserSid">S-1-5-82-604604840-3341247844-1790606609-4006251754-2470522317</Data> 
  <Data Name="SubjectUserName">RDWebAccess</Data> 
  <Data Name="SubjectDomainName">IIS APPPOOL</Data> 
  <Data Name="SubjectLogonId">0x234ed94</Data> 
  <Data Name="TargetUserSid">S-1-0-0</Data> 
  <Data Name="TargetUserName">olivierbn, b</Data> 
  <Data Name="TargetDomainName">eao</Data> 
  <Data Name="Status">0xc000006d</Data> 
  <Data Name="FailureReason">%%2313</Data> 
  <Data Name="SubStatus">0xc0000064</Data> 
  <Data Name="LogonType">3</Data> 
  <Data Name="LogonProcessName">Advapi</Data> 
  <Data Name="AuthenticationPackageName">Negotiate</Data> 
  <Data Name="WorkstationName">EAO-CAL</Data> 
  <Data Name="TransmittedServices">-</Data> 
  <Data Name="LmPackageName">-</Data> 
  <Data Name="KeyLength">0</Data> 
  <Data Name="ProcessId">0x1688</Data> 
  <Data Name="ProcessName">C:\Windows\System32\inetsrv\w3wp.exe</Data> 
  <Data Name="IpAddress">-</Data> 
  <Data Name="IpPort">-</Data> 
  </EventData>
  </Event>`

**Comment by rabi29** [comment]
sorry :)

[xml.txt](https://github.com/jjxtra/Windows-IP-Ban-Service/files/1246273/xml.txt)

**Comment by jjxtra** [comment]
Doesn't look possible, XML does not have the ip address.
