### ISSUE TITLE
Group in firewall rules and error in banlog.txt creation

### ISSUE THREAD

**Issue by Francesco-Cocchioni** [jjxtra/Windows-IP-Ban-Service#30]
Hello,

it would be useful if in the firewall rules create by IPBan, the "Group" property is set.

That is adding the following line

rule.Grouping = "IPBan";

between line 77 and 78 of IPBanWindowsFirewall.cs. 

The information about the firewall rule group is useful for example for the "Secure Rules" feature of "Windows Firewall Control" application.

Regarding the banlog.txt creation i think that there is an error in the code. On line 55 of IPBanService.cs the list of IP that need to be saved is stored inside the variable ipBlockerDate and not inside the variable ipBlocker.

With the current code every time an IP is banned all the IP in memory, including the ones which have a number of failed login below the FailedLoginAttemptsBeforeBan threshold, are saved inside the banlog.txt. Then if the IPBan service is restarted and the BanFileClearOnRestart is set on false, those IP which have not been banned before IPBan restart (that is the IP which were inside ipBlocker but not inside ipBlockerDate) are now banned (when IPBan restart) inside the function ProcessBanFileOnStart.

Generally i think that the BanFileClearOnRestart features need to be improved, storing inside the banlog.txt for each IP also the datetime when the ban occurred. Then inside ProcessBanFileOnStart this stored date should be loaded and used instead of DateTime.UtcNow for each banned IP.

**Comment by jjxtra** [comment]
I've made these changes, just pushed to master.
