### ISSUE TITLE
Using DNS server that IPBan exists on results in ban of that client with laptops only

### ISSUE THREAD

**Issue by BlackHoleFox** [jjxtra/Windows-IP-Ban-Service#36]
I looked into why my laptop was unable to ping my DNS server and found that IPBan had blocked it. I cleared the ban list and one web search worked before it was banned again. It inst even touching MS Exchange, Remote Desktop, or SQL.

Any insight into why this is happening? The laptops IPv4 address isnt in the perma ban list either.

Extra Info: It bans its IPv6 address first after a single web search, then proceeds to ban the IPv4 address after a ping.

**Comment by jjxtra** [comment]
No idea. You'll have to check the event viewer for your ip address to see what is failing to login.

**Comment by BlackHoleFox** [comment]
Event viewer on the laptop or the server?

**Comment by jjxtra** [comment]
Any luck looking through those event viewer logs?

**Comment by BlackHoleFox** [comment]
My apologies for the delay. I am currently out of town due to a family member's poor health, so it will be a few days until I can check. If possible, please bear with until I can get a chance to look thoroughly.

**Comment by jjxtra** [comment]
No rush, take your time, hope things work out...

**Comment by BlackHoleFox** [comment]
I was unable to find any event related to my laptop, and it doesn't event seem to be happening anymore. DNS requests are working fine and pinging it is functioning as well. Closing this for now as it wont reproduce anymore. I will reopen it if I can find anything solid to figure out why it did happen at all.
